services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.5
    container_name: tpapp-keycloak
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
      - ./infra/keycloak:/opt/keycloak/data/import